#!/usr/bin/env node
// One-time setup for new developers. Safe to re-run — every step is idempotent.
// Extend by adding more step functions below and calling them from main().

import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(import.meta.dirname, "..");

// The keys below are baked into the Supabase CLI binary — every developer
// running the same CLI version gets identical values, so it's safe to hardcode.
// If Supabase ever rotates the hardcoded dev keys in a future CLI release, these
// defaults would drift from what `supabase start` actually prints; fix is a
// one-line edit here when bumping the `supabase` devDependency.
//
// The secret key is used by the e2e session-minting helper to create and delete
// test users via the Supabase Admin API; it is never shipped to production.
const LOCAL_ENV = `# Local development environment — generated by \`npm run setup\`.
# These are the deterministic defaults produced by \`npx supabase start\`.
# Do not commit — .env.local is gitignored.

NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH
SUPABASE_SECRET_KEY=sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz
DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:54322/postgres

# E2E test-user credentials + reset-endpoint token. Values are
# arbitrary for local dev — they just need to match what
# scripts/seed-e2e-users.mjs applies and what Playwright reads.
# Production uses separate values set in Vercel + GH Actions secrets
# (see docs/doc-supabase.md).
E2E_REGULAR_PASSWORD=local-e2e-regular-pw
E2E_ADMIN_PASSWORD=local-e2e-admin-pw
CI_RESET_TOKEN=local-reset-token
`;

function ensureLocalEnv() {
  const path = resolve(repoRoot, ".env.local");
  if (existsSync(path)) {
    console.log("  .env.local already exists — leaving it alone");
    return;
  }
  writeFileSync(path, LOCAL_ENV);
  console.log("  created .env.local with local Supabase defaults");
}

function main() {
  console.log("Setting up is-app for local development...\n");

  console.log("1. (and only step currently) Environment file");
  ensureLocalEnv();

  console.log("\nDone. Next: run `npm run dev` (Docker Desktop must be running).");
}

main();
