#!/usr/bin/env node
// One-time setup for new developers. Safe to re-run — every step is idempotent.
// Extend by adding more step functions below and calling them from main().

import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(import.meta.dirname, "..");

// The publishable key below is baked into the Supabase CLI binary — every
// developer running the same CLI version gets the identical key, so it's safe
// to hardcode. If Supabase ever rotates the hardcoded dev key in a future CLI
// release, this default would drift from what `supabase start` actually prints;
// fix is a one-line edit here when bumping the `supabase` devDependency.
const LOCAL_ENV = `# Local development environment — generated by \`npm run setup\`.
# These are the deterministic defaults produced by \`npx supabase start\`.
# Do not commit — .env.local is gitignored.

NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH
DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:54322/postgres
`;

function ensureLocalEnv() {
  const path = resolve(repoRoot, ".env.local");
  if (existsSync(path)) {
    console.log("  .env.local already exists — leaving it alone");
    return;
  }
  writeFileSync(path, LOCAL_ENV);
  console.log("  created .env.local with local Supabase defaults");
}

function main() {
  console.log("Setting up is-app for local development...\n");

  console.log("1. (and only step currently) Environment file");
  ensureLocalEnv();

  console.log("\nDone. Next: run `npm run dev` (Docker Desktop must be running).");
}

main();
